[project]
name = "doggelganger"
version = "0.1.1"
description = "Find you canine look alike!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "litestar[standard]>=2.11.0",
    "pillow>=10.4.0",
    "torch==2.4.1 ; sys_platform == 'darwin' and platform_machine == 'arm64'",
    "torch==2.4.1+cpu ; sys_platform !='darwin'",
    "transformers>=4.44.2",
    "vecs>=0.4.4",
]

[project.optional-dependencies]
train = [
    "scikit-learn>=1.5.2",
]

[project.scripts]
train = "doggelganger.train:main"
serve = "doggelganger.serve:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch]
metadata.allow-direct-references = true

[tool.uv]
dev-dependencies = [
    "pytest-mock>=3.14.0",
    "pytest>=8.3.3",
    "python-dotenv>=1.0.1",
    "ruff>=0.6.5",
    "torch==2.4.1"
]
index-strategy = "unsafe-best-match"
extra-index-url = ["https://download.pytorch.org/whl/cpu"]