[project]
name = "doggelganger"
version = "0.1.1"
description = "Find you canine look alike!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "litestar[standard]>=2.11.0",
    "pillow>=10.4.0",
    "torch==2.4.1 ; sys_platform == 'darwin' and platform_machine == 'arm64'",
    "torch==2.4.1+cpu ; sys_platform !='darwin'",
    "transformers>=4.44.2",
    "vecs>=0.4.4",
]

[project.optional-dependencies]
train = [
    "scikit-learn>=1.5.2",
]

[project.scripts]
embed = "doggelganger.embeddings:main"
serve = "doggelganger.serve:main"
train = "doggelganger.train:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch]
metadata.allow-direct-references = true

[tool.uv]
dev-dependencies = [
    "optuna>=4.0.0",
    "pytest-mock>=3.14.0",
    "pytest>=8.3.3",
    "python-dotenv>=1.0.1",
    "ruff>=0.6.5",
    "selenium>=4.25.0",
    "tensorboard>=2.18.0",
    "torch==2.4.1",
    "torchvision==0.19.1",
    "webdriver-manager>=4.0.2",
    "xgboost>=2.1.1",
]
index-strategy = "unsafe-best-match"
extra-index-url = ["https://download.pytorch.org/whl/cpu"]
