name: Test and release
on:
  push:

jobs:
  lint-check:
    name: "Lint: ruff check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

  lint-format:
    name: "Lint: ruff format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: format

  test:                                                                                                                                                   
    name:  "Test: pytest"
    runs-on: ubuntu-latest                                                                                                                                
    steps:                                                                                                                                                
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version" 
      
      - name: Install everything
        run: uv sync --all-groups
      - name: Run tests
        run: uv run pytest tests --cov=src/ --cov-report=xml 
      - uses: codecov/codecov-action@v3 

  docker-release:
    name: Tagged Docker release to Google Artifact Registry
    runs-on: ubuntu-24.04
    needs: [lint, test]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/371619654395/locations/global/workloadIdentityPools/doggelganger-production/providers/doggelganger-github
          service_account: doggelganger-service@doggelganger.iam.gserviceaccount.com
          access_token_lifetime: 600s

      - 
        name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-east4-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      
      -
        name: Build and Push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          tags: |
            us-east4-docker.pkg.dev/doggelganger/doggelganger/serve:${{ github.ref_name }}
            us-east4-docker.pkg.dev/doggelganger/doggelganger/serve:latest
          push: true
          platforms: linux/amd64 
          provenance: false