name: Test and release
on:
  push:

jobs:
  # test-python:
  #   name: Test Python code
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

      # - id: install
      #   name: Install Python, pipenv and Pipfile packages
      #   uses: palewire/install-python-pipenv-pipfile@v2
      #   with:
      #     python-version: 3.11

      # - id: run
      #   name: Run tests
      #   run: pytest .

  docker-release:
    name: Tagged Docker release to Google Artifact Registry
    runs-on: ubuntu-latest
    # needs: [test-python]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/371619654395/locations/global/workloadIdentityPools/doggelganger-production/providers/doggelganger-github
          service_account: doggelganger-service@doggelganger.iam.gserviceaccount.com
          access_token_lifetime: 600s

      - 
        name: Login to Artifact Registry
        uses: redhat-actions/podman-login@v1.7
        with:
          registry: us-east4-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      
      - id: build-image
        name: Buildah Build
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: serve.Dockerfile
          image: us-east4-docker.pkg.dev/doggelganger/doggelganger/serve
          tags: latest ${{ github.ref_name }}
          platform: linux/amd64

      - id: push-to-registry
        name: Push to Google Artifact Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}