name: Test and release
on:
  push:

jobs:
  # test-python:
  #   name: Test Python code
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

      # - id: install
      #   name: Install Python, pipenv and Pipfile packages
      #   uses: palewire/install-python-pipenv-pipfile@v2
      #   with:
      #     python-version: 3.11

      # - id: run
      #   name: Run tests
      #   run: pytest .

  docker-release:
    name: Tagged Docker release to Google Artifact Registry
    runs-on: ubuntu-latest
    # needs: [test-python]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/371619654395/locations/global/workloadIdentityPools/doggelganger-production/providers/doggelganger-github
          service_account: doggelganger-service@doggelganger.iam.gserviceaccount.com
          access_token_lifetime: 600s

      - 
        name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-east4-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: doggelganger/serve.Dockerfile
          push: true
          # necessary for Google Artifact Registry; otherwise looks like three images
          provenance: false
          tags: |
            us-east4-docker.pkg.dev/doggelganger/doggelganger/serve:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max